kind: pipeline
name: default

steps:
- name: Build and Package Application
image: maven:3.8.6-openjdk-17
commands:
- mvn clean package -DskipTests
- echo "Listing files in target directory"
- ls -la target/
artifacts:
- target/*.jar

- name: Copy Files to Server
image: appleboy/drone-scp
settings:
host: ${DO_DROPLET_IP} # Using secret for host
username: ${DO_DROPLET_USER} # Using secret for username
key: ${DO_PRIVATE_KEY} # Using secret for private key
source: "target/*.jar" # Ensure the file exists and matches the path
target: "/path/to/target/directory/"
when:
status: success
